INSERT INTO PRODUCT (ID, ANIMAL, CATEGORY, SIZE, AGE, NAME) VALUES ('1010', 'DOG', 'FOOD', 'SMALL', 'PUPPY', 'Chunky Perros pequenos Pollo 25 Kg');
INSERT INTO PRODUCT (ID, ANIMAL, CATEGORY, SIZE, AGE, NAME) VALUES ('2020', 'DOG', 'FOOD', 'MEDIUM', 'SENIOR', 'Dog Chow Perros Senior Vida Sana 17 Kg');
INSERT INTO PRODUCT (ID, ANIMAL, CATEGORY, SIZE, AGE, NAME) VALUES ('3030', 'DOG', 'FOOD', 'BIG', 'ADULT', 'Nutra-Nuggets Perros Adultos Pollo y Arroz 15 Kg');
INSERT INTO PRODUCT (ID, ANIMAL, CATEGORY, SIZE, AGE, NAME) VALUES ('4040', 'DOG', 'FOOD', 'SMALL', 'PUPPY', 'Chunky Delicaprichos Perros Tocineta 160 g');
INSERT INTO PRODUCT (ID, ANIMAL, CATEGORY, SIZE, AGE, NAME) VALUES ('5050', 'DOG', 'FOOD', 'SMALL', 'PUPPY', 'Galletas Dog Chow 300 g');

INSERT INTO PRODUCT (ID, ANIMAL, CATEGORY, SIZE, AGE, NAME) VALUES ('6060', 'CAT', 'FOOD', 'MEDIUM', 'ADULT', 'Churu Snack Tuna Whit Scallop Paquete x 10 Unds');
INSERT INTO PRODUCT (ID, ANIMAL, CATEGORY, SIZE, AGE, NAME) VALUES ('7070', 'CAT', 'FOOD', 'SMALL', 'PUPPY', 'Pixie para gatos dieta de pescado 200 g');
INSERT INTO PRODUCT (ID, ANIMAL, CATEGORY, SIZE, AGE, NAME) VALUES ('8080', 'CAT', 'FOOD', 'MEDIUM', 'ADULT', 'Hills Prescription Lata 5.5 Oz');
INSERT INTO PRODUCT (ID, ANIMAL, CATEGORY, SIZE, AGE, NAME) VALUES ('8004', 'CAT', 'FOOD', 'SMALL', 'PUPPY', 'Felix Comida Húmeda Gatos Paté Pavo 156 g');
INSERT INTO PRODUCT (ID, ANIMAL, CATEGORY, SIZE, AGE, NAME) VALUES ('1001', 'CAT', 'FOOD', 'MEDIUM', 'PUPPY', 'Comida Húmeda NutreCat Gourmet sabor Atún y Pargo por 85 g');

INSERT INTO INVENTARY (ID, PRODUCT_ID, AMOUNT, PRICE, AVAILABLE) VALUES ('1001', '1010', 5, 70, TRUE);
INSERT INTO INVENTARY (ID, PRODUCT_ID, AMOUNT, PRICE, AVAILABLE) VALUES ('1002', '2020', 5, 50, TRUE);
INSERT INTO INVENTARY (ID, PRODUCT_ID, AMOUNT, PRICE, AVAILABLE) VALUES ('1003', '3030', 2, 30, TRUE);
INSERT INTO INVENTARY (ID, PRODUCT_ID, AMOUNT, PRICE, AVAILABLE) VALUES ('1004', '4040', 5, 25, TRUE);
INSERT INTO INVENTARY (ID, PRODUCT_ID, AMOUNT, PRICE, AVAILABLE) VALUES ('1005', '5050', 3, 50, TRUE);
INSERT INTO INVENTARY (ID, PRODUCT_ID, AMOUNT, PRICE, AVAILABLE) VALUES ('1006', '6060', 2, 50, TRUE);
INSERT INTO INVENTARY (ID, PRODUCT_ID, AMOUNT, PRICE, AVAILABLE) VALUES ('1007', '7070', 3, 50, TRUE);
INSERT INTO INVENTARY (ID, PRODUCT_ID, AMOUNT, PRICE, AVAILABLE) VALUES ('1008', '8080', 3, 50, TRUE);